/* This file is generated. Do not modify by hand. */

import DtoExceptions

public typealias InvalidPacketExceptionData = DtoExceptions.InvalidPacketExceptionData
public typealias DeviceAddressConflictExceptionData = DtoExceptions.DeviceAddressConflictExceptionData
public typealias MovementInterruptedExceptionData = DtoExceptions.MovementInterruptedExceptionData
public typealias StreamMovementInterruptedExceptionData = DtoExceptions.StreamMovementInterruptedExceptionData
public typealias PvtMovementInterruptedExceptionData = DtoExceptions.PvtMovementInterruptedExceptionData
public typealias MovementFailedExceptionData = DtoExceptions.MovementFailedExceptionData
public typealias StreamMovementFailedExceptionData = DtoExceptions.StreamMovementFailedExceptionData
public typealias PvtMovementFailedExceptionData = DtoExceptions.PvtMovementFailedExceptionData
public typealias StreamExecutionExceptionData = DtoExceptions.StreamExecutionExceptionData
public typealias PvtExecutionExceptionData = DtoExceptions.PvtExecutionExceptionData
public typealias InvalidPvtPoint = DtoExceptions.InvalidPvtPoint
public typealias OperationFailedExceptionData = DtoExceptions.OperationFailedExceptionData
public typealias InvalidResponseExceptionData = DtoExceptions.InvalidResponseExceptionData
public typealias CommandFailedExceptionData = DtoExceptions.CommandFailedExceptionData
public typealias BinaryCommandFailedExceptionData = DtoExceptions.BinaryCommandFailedExceptionData
public typealias SetPeripheralStateExceptionData = DtoExceptions.SetPeripheralStateExceptionData
public typealias SetDeviceStateExceptionData = DtoExceptions.SetDeviceStateExceptionData
public typealias CommandTooLongExceptionData = DtoExceptions.CommandTooLongExceptionData
public typealias DeviceDbFailedExceptionData = DtoExceptions.DeviceDbFailedExceptionData
public typealias GCodeSyntaxExceptionData = DtoExceptions.GCodeSyntaxExceptionData
public typealias GCodeExecutionExceptionData = DtoExceptions.GCodeExecutionExceptionData
